---

name: Helm Charts Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        type: string
permissions:
  contents: write
  packages: write
run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@main
        with:
          tag-name: '${{ inputs.release }}'
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  chart-release-prepare:
    needs: [check-tag]
    runs-on: ubuntu-latest
    outputs:
      images-versions: ${{ steps.update-versions.outputs.images-versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Update versions in values"
        id: update-versions
        uses: netcracker/qubership-workflow-hub/actions/helm-charts-release@v1.0.3
        with:
          release-version: ${{ inputs.release }}
          chart-version: "0.1.0"
          config-file: .github/helm-charts-release-config.yaml
        env:
          ${{ insert }}: ${{ vars }}
      - name: "Debug"
        run: |
          echo "Images versions: ${{ steps.update-versions.outputs.images-versions }}"

  charts-release:
    needs: [chart-release-prepare]
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release-${{ inputs.release }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        #continue-on-error: true
        uses: netcracker/chart-releaser-action@main
        with:
          charts_dir: chart/helm
          release_name_template: ${{ inputs.release }}
          skip_existing: true
          skip_upload: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Release-drafter"
        uses: netcracker/release-drafter@master
        with:
          config-name: release-drafter-config.yml
          publish: true
          name: ${{ inputs.release }}
          tag: ${{ inputs.release }}
          version: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Assets
        uses: netcracker/qubership-workflow-hub/actions/assets-action@main
        with:
          tag: ${{ inputs.release }}
          item-path: .cr-release-packages/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
